# Nombre del workflow que aparecerá en la interfaz de GitHub Actions
name: Run Tests

# Define cuándo se ejecutará este workflow
on:
  # Se ejecuta cuando se hace push a las siguientes ramas
  push:
    branches: [ main, master, develop ]
  # Se ejecuta cuando se crea un pull request hacia estas ramas
  pull_request:
    branches: [ main, master, develop ]

# Define los trabajos (jobs) que se ejecutarán
jobs:
  # Nombre del trabajo
  test:
    # Sistema operativo donde se ejecutará el job (Ubuntu más reciente)
    runs-on: ubuntu-latest

    # Estrategia de matriz para ejecutar el job múltiples veces con diferentes configuraciones
    strategy:
      matrix:
        # Define las versiones de Node.js que se probarán (crea 2 jobs paralelos)
        node-version: [18.x, 20.x]

    # Pasos que se ejecutarán en este job
    steps:
    # Descarga el código fuente del repositorio en el runner
    - uses: actions/checkout@v4
    
    # Configura Node.js con la versión especificada en la matriz
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        # Usa la versión de Node.js actual de la matriz
        node-version: ${{ matrix.node-version }}
        # Habilita el cache de npm para acelerar las instalaciones
        cache: 'npm'
    
    # Instala las dependencias del proyecto usando npm ci
    - name: Install dependencies
      run: npm ci
    
    # Ejecuta los tests del proyecto
    - name: Run tests
      run: npm test
